import type { Metadata } from 'next'
// 1. Import Inter instead of Geist
import { Inter, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import ScrollToTopButton from './components/ScrollToTopButton'
import { HelpSidebar } from './components/HelpSlider'
import { SessionProvider } from 'next-auth/react'
import NextAuthProvider from '@/provider/NextAuthProvider'
import { Toaster } from 'sonner'
import { ClientToaster } from './components/ClientToaster'
// 2. Initialize Inter and create a CSS variable for it
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

// We can keep Geist Mono for your monospace font
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Jubutix | Digital Marketing Agency',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      {/* 3. Apply the new --font-inter variable to the body */}
      <body  className={`${inter.variable} ${geistMono.variable} antialiased `}>
        <NextAuthProvider>
          <ClientToaster />
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
          <ScrollToTopButton />
          <HelpSidebar />
        </NextAuthProvider>
      </body>
    </html>
  )
}
