import type { Metadata } from 'next'
import { GoogleTagManager } from '@next/third-parties/google'

import { Inter, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import ScrollToTopButton from './components/ScrollToTopButton'
import { HelpSidebar } from './components/HelpSlider'

import NextAuthProvider from '@/provider/NextAuthProvider'

import { ClientToaster } from './components/ClientToaster'
// 2. Initialize Inter and create a CSS variable for it
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Jubutix | Digital Marketing Agency',
  description: 'Generated by create next app',
  verification: {
    google: `${process.env.GSC_ID}`,
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <GoogleTagManager gtmId={`${process.env.GTM_ID}`} />

      <body className={`${inter.variable} ${geistMono.variable} antialiased `}>
        <NextAuthProvider>
          <ClientToaster />
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
          <ScrollToTopButton />
          <HelpSidebar />
        </NextAuthProvider>
      </body>
    </html>
  )
}
